server:
  port: 8082
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # Оптимизация для стриминга
  tomcat:
    connection-timeout: 20000
    max-connections: 200
    threads:
      max: 200
      min-spare: 10

app:
  movies:
    directory: ./movies

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  websocket:
    sockjs:
      heartbeat-time: 25000
      disconnect-delay: 5000

  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB

  # Оптимизация для статических ресурсов
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 0
          no-cache: true
          no-store: true

# Настройки логирования
logging:
  level:
    org.example.syncwatchservice: DEBUG
    org.springframework.web.socket: DEBUG
    # Убираем избыточные логи
    org.apache.coyote.http11.Http11InputBuffer: WARN
    org.apache.coyote.http11.Http11Processor: WARN

# Настройки JVM для улучшения работы со стримингом
management:
  endpoints:
    web:
      exposure:
        include: health,info